/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.contactmanagementsystem.views;

import com.contactmanagementsystem.models.Contact;
import com.contactmanagementsystem.service.impl.ContactService;
import com.contactmanagementsystem.service.impl.UserService;
import com.contactmanagementsystem.tablesmodels.TableModel;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author dagy
 */
public class ContactForm extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement ps;
    ResultSet rs;

    UserService userService = new UserService();

    ContactService contactService;

    public static int currentUserId;

    String imagePath = null;
    
    int position = 0;

    /**
     * Creates new form ContactForm
     */
    public ContactForm() {
        initComponents();
        this.populateJTable();

        jTableContact.setShowGrid(true);
        jTableContact.setGridColor(Color.GREEN);
        jTableContact.setSelectionBackground(Color.lightGray);

        System.out.println(currentUserId + "Contact form");

//        JTableHeader th = jTableContact.getTableHeader();
//        th.setForeground(Color.green);
//        th.setFont(new Font("Ubuntu", Font.BOLD, 16));
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinus = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelUserPicture = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelAddress = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelTitle6 = new javax.swing.JLabel();
        jLabelPicture = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelGroup = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableContact = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelFirstName1 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAddContact = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setMinimumSize(new java.awt.Dimension(436, 260));
        jPanel2.setPreferredSize(new java.awt.Dimension(862, 500));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(46, 204, 113));
        jPanel3.setPreferredSize(new java.awt.Dimension(436, 60));

        jLabelClose.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 0, 0));
        jLabelClose.setText("x");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMinus.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelMinus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinus.setText("-");
        jLabelMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinus.setPreferredSize(new java.awt.Dimension(13, 29));
        jLabelMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinusMouseClicked(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText(" My Contact");

        jLabelUserPicture.setBackground(new java.awt.Color(255, 255, 0));
        jLabelUserPicture.setOpaque(true);

        jLabelUserName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(253, 227, 167));
        jLabelUserName.setText("Username");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelUserPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303)
                .addComponent(jLabelMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelUserName))
                .addContainerGap())
            .addComponent(jLabelUserPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelLastName.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelLastName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLastName.setText("Last name :");

        jLabelId.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("Id");

        jTextFieldLastName.setBackground(new java.awt.Color(116, 177, 239));
        jTextFieldLastName.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextFieldLastName.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPhone.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhone.setText("Phone :");

        jTextFieldPhone.setBackground(new java.awt.Color(116, 177, 239));
        jTextFieldPhone.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });

        jLabelAddress.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelAddress.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAddress.setText("Address : ");

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(116, 177, 239));
        jTextFieldId.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTitle6.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelTitle6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle6.setText("Profile Picture");

        jLabelPicture.setBackground(new java.awt.Color(116, 177, 239));
        jLabelPicture.setOpaque(true);

        jButtonBrowse.setText("Browse");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email :");

        jTextFieldEmail.setBackground(new java.awt.Color(116, 177, 239));
        jTextFieldEmail.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setText("  ");

        jLabelGroup.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelGroup.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGroup.setText("Group : ");

        jComboBoxGroup.setBackground(new java.awt.Color(116, 177, 239));
        jComboBoxGroup.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jComboBoxGroup.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Work" }));

        jTextAreaAddress.setBackground(new java.awt.Color(116, 177, 239));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setForeground(new java.awt.Color(255, 255, 255));
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jTableContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableContactMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableContact);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldFirstName.setBackground(new java.awt.Color(116, 177, 239));
        jTextFieldFirstName.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jTextFieldFirstName.setForeground(new java.awt.Color(255, 255, 255));

        jLabelFirstName1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabelFirstName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFirstName1.setText("Fisrt name :");

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(242, 38, 19));
        jButtonDelete.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(242, 162, 63));
        jButtonUpdate.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAddContact.setBackground(new java.awt.Color(46, 204, 113));
        jButtonAddContact.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonAddContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact.setText("Create");
        jButtonAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddContact, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddContact)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );

        jButtonFirst.setText("<<");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("<");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonNext.setText(">");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonLast.setText(">>");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelGroup)
                            .addComponent(jLabelFirstName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLast, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAddress))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelId))
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFirstName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFirst)
                            .addComponent(jButtonPrevious)
                            .addComponent(jButtonNext)
                            .addComponent(jButtonLast))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButtonBrowse)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButtonReset)
                                        .addGap(45, 45, 45))
                                    .addComponent(jLabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(jLabelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
        //
        imagePath = contactService.browseImage(jLabelPicture);

        System.out.println(imagePath);
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    public boolean verifiedData() {
        // verifie if first name, last name, password are empty
        if (jTextFieldFirstName.getText().equals("") && jTextFieldLastName.getText().equals("")
                || jTextFieldPhone.getText().equals("") || jTextFieldEmail.getText().equals("")
                || jTextAreaAddress.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vide");
            return false;
        } // if no image are selected
        else if (imagePath == null) {
            JOptionPane.showMessageDialog(null, "Aucune image selectionnee");
            return false;
        } // if everything are ok
        else {
            return true;
        }

    }

    // verifier si l'utilisateur existe
    public boolean isContactExist(String firstName, String lastName) {

        boolean userExist = false;

        userExist = contactService.findContactExist(firstName, lastName);

        return userExist;
    }

    private void jButtonAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContactActionPerformed
//        long id = Long.valueOf(jTextFieldId.getText());
        String firstName = jTextFieldFirstName.getText();
        String lastName = jTextFieldLastName.getText();
        String phone = jTextFieldPhone.getText();
        String email = jTextFieldEmail.getText();
        String address = jTextAreaAddress.getText();
        String group = jComboBoxGroup.getSelectedItem().toString();

        contactService = new ContactService();

//        byte[] img = null;
        Contact contact;

        //you can cheick if all fields are empty
        if (verifiedData()) {

            byte[] img = null;

            if (imagePath != null) {
                try {
                    Path path = Paths.get(imagePath);
                    img = Files.readAllBytes(path);
                    //InputStream image = new FileInputStream(new File(imagePath));
                    contact = new Contact(null, firstName, lastName, phone, email, group, address, img, (int) currentUserId);

                    contactService.creat(contact);

                    refreshJTable();
                    
                    this.clearContactFiels();

                } catch (IOException ex) {
                    Logger.getLogger(ContactForm.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }

    }//GEN-LAST:event_jButtonAddContactActionPerformed

    private void jLabelMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinusMouseClicked
        // TODO reduire la fenetre:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinusMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO fermer la fenetre:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTableContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContactMouseClicked
        // TODO display selected JTable row data:

        int rowIndex = jTableContact.getSelectedRow();

        
        jTextFieldId.setText(jTableContact.getValueAt(rowIndex, 0).toString());
        jTextFieldFirstName.setText(jTableContact.getValueAt(rowIndex, 1).toString());
        jTextFieldLastName.setText(jTableContact.getValueAt(rowIndex, 2).toString());

        // pour le combobox
        
         jTextFieldPhone.setText(jTableContact.getValueAt(rowIndex, 3).toString());
         
        jTextFieldEmail.setText(jTableContact.getValueAt(rowIndex, 5).toString());
        
        jComboBoxGroup.setSelectedItem(jTableContact.getValueAt(rowIndex, 3).toString());
       
        jTextAreaAddress.setText(jTableContact.getValueAt(rowIndex, 6).toString());

        // image
        Image img = ((ImageIcon) jTableContact.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabelPicture.getWidth(), jLabelPicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(img);
        jLabelPicture.setIcon(imageIcon);

    }//GEN-LAST:event_jTableContactMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        if (!jTextFieldId.getText().equals("")) {
            long id = Long.valueOf(jTextFieldId.getText());
            String firstName = jTextFieldFirstName.getText();
            String lastName = jTextFieldLastName.getText();
            String phone = jTextFieldPhone.getText();
            String email = jTextFieldEmail.getText();
            String address = jTextAreaAddress.getText();
            String group = jComboBoxGroup.getSelectedItem().toString();

            // if thne user want to update the data and the image
            if (imagePath != null) {

                byte[] img = null;

                try {
                    Path path = Paths.get(imagePath);

                    img = Files.readAllBytes(path);
                    //InputStream image = new FileInputStream(new File(imagePath));
                    Contact contact = new Contact(id, firstName, lastName, phone, email, group, address, img, currentUserId);

                    contactService.updateContact(contact, true);

                    refreshJTable();

                    clearContactFiels();

                } catch (IOException ex) {
                    Logger.getLogger(ContactForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                Contact contact = new Contact(id, firstName, lastName, phone, email, group, address, null, currentUserId);

                contactService.updateContact(contact, false);

                refreshJTable();

                clearContactFiels();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select a contact from table");
        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:

        if (!jTextFieldId.getText().equals("")) {

            long id = Long.valueOf(jTextFieldId.getText());

            contactService.deleteContact(id);

            refreshJTable();
            
            clearContactFiels();

            
        } else {
            JOptionPane.showMessageDialog(null, "Select a contact from table");
        }

    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO reset contact form: 
        clearContactFiels();

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        // TODO add your handling code here:
        position = 0;
        showData(position);
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        // TODO add your handling code here:
        
        position = jTableContact.getRowCount() - 1;
        
        showData(position);
      
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        position++;
        showData(position);
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO :
        position--;
        showData(position);
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    public void showData(int index){
        jTextFieldId.setText(jTableContact.getValueAt(index, 0).toString());
        jTextFieldFirstName.setText(jTableContact.getValueAt(index, 1).toString());
        jTextFieldLastName.setText(jTableContact.getValueAt(index, 2).toString());

        // pour le combobox
        
         jTextFieldPhone.setText(jTableContact.getValueAt(index, 3).toString());
         
        jTextFieldEmail.setText(jTableContact.getValueAt(index, 5).toString());
        
        jComboBoxGroup.setSelectedItem(jTableContact.getValueAt(index, 3).toString());
       
        jTextAreaAddress.setText(jTableContact.getValueAt(index, 6).toString());

        // image
        Image img = ((ImageIcon) jTableContact.getValueAt(index, 7)).getImage().getScaledInstance(jLabelPicture.getWidth(), jLabelPicture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(img);
        jLabelPicture.setIcon(imageIcon);

    }
    
    public Contact getContact() {
        String id = jTextFieldId.getText();
        String firstName = jTextFieldFirstName.getText();
        String lastName = jTextFieldLastName.getText();
        String phone = jTextFieldPhone.getText();
        String email = jTextFieldEmail.getText();
        String address = jTextAreaAddress.getText();
        String group = jComboBoxGroup.getSelectedItem().toString();

        byte[] img = null;

        try {
            Path path = Paths.get(imagePath);
            img = Files.readAllBytes(path);
            //InputStream image = new FileInputStream(new File(imagePath));
        } catch (IOException ex) {
            Logger.getLogger(ContactForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        Contact contact = new Contact(null, firstName, lastName, phone, email, group, address, img, (int) currentUserId);

        return contact;
    }

    public void clearContactFiels() {
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldId.setText("");
        jTextFieldPhone.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGroup.setSelectedIndex(0);
        jTextAreaAddress.setText("");
        jLabelPicture.setIcon(null);
        
        // set imagePath to null to prevent the user to add unwanted duplicated image
        imagePath = null;
        refreshJTable();
    }

    public void populateJTable() {

        contactService = new ContactService();

//        List<Contact> contacts = contactService.contactList(currentUserId);
        List<Contact> contacts = contactService.findContactByUserId(currentUserId);
        /**
         * `id`, `first_name`, `last_name`, `contact_group`, `phone`, `email`,
         * `address`, `picture`, `user_id`
         *
         * initialiser les colonnes
         */
        String[] colNames = {"Id", "First Name", "Last Name",
            "Phone", "Email", "Group", "Address", "Picture"};
        //initialiser les ligne
        Object[][] rows = new Object[contacts.size()][8];

        for (int i = 0; i < contacts.size(); i++) {
            rows[i][0] = contacts.get(i).getId();
            rows[i][1] = contacts.get(i).getFirstName();
            rows[i][2] = contacts.get(i).getLastName();
            rows[i][3] = contacts.get(i).getContactGroup();
            rows[i][4] = contacts.get(i).getPhone();
            rows[i][5] = contacts.get(i).getEmail();
            rows[i][6] = contacts.get(i).getAddress();
            ImageIcon pic = new ImageIcon(new ImageIcon(contacts.get(i).getPicture())
                    .getImage().getScaledInstance(80, 50, Image.SCALE_SMOOTH));
            rows[i][7] = pic;
            //rows[i][8] = "";
        }

        //
        TableModel contactTable = new TableModel(rows, colNames);
        jTableContact.setModel(contactTable);
        jTableContact.setRowHeight(50);
        jTableContact.getColumnModel().getColumn(7).setPreferredWidth(80);

    }

    public void refreshJTable() {
        jTableContact.setModel(new DefaultTableModel());
        populateJTable();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddContact;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName1;
    private javax.swing.JLabel jLabelGroup;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelMinus;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle6;
    public javax.swing.JLabel jLabelUserName;
    public javax.swing.JLabel jLabelUserPicture;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableContact;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
